osbuild/weldr-client

.github/workflows/tests.yml
Without this it would modify go.mod and linting would fail.
=> actions: Install lint using GOPATH

weldr-client.spec.in
And their version numbers include the 34.x range. The weldr-client
version starts with 35.0 (even on the F34 release).
Fix #5
=> The rpm package should obsolete composer-cli from lorax

cmd/composer-cli/root/test_utilities.go
@bcl does this change look correct?  Certainly the opposite doesn't look right to me.
=> ExcuteTests - return the correct error variables in case of errors

cmd/composer-cli/compose/results.go, cmd/composer-cli/compose/results_test.go
In the previous version of composer-cli it printed the download
progress. This isn't currently possible, so just print the filename when
it is finished.
Fixes #15
=> Print filename for compose results

Makefile, weldr-client.spec.in
Make it easier to build rpms for testing and development. These targets
skip the gpg signature check so DO NOT USE IN PRODUCTION
Also move the rpm builddep to a makefile target instead of requiring
sudo every time you run make with rpm or scratch-rpm
=> Makefile: Add scratch-srpm and scratch-rpm targets

weldr/compose_test.go, weldr/sources_test.go
osbuild-composer v31 returns a more detailed error for
TestStartComposeBadType, so that has been changed.
The number of image types returned depends on the distribution being
used, so change to looking for >= 6 of them.
The source type depends on the first repo in the list, so it could be
any of the supported types. They all start with "yum-" so change the
test to look for that instead.
=> tests: Fix integration tests

weldr-client.spec.in
The RHEL macros are not as flexible in RHEL 8 so this changes how
weldr-client is built on all RHEL releases for consistency, and cleans
up the order a bit (rhel first, fedora second in all cases).
=> spec: Adjust build methods for RHEL 8

weldr-client.spec.in
The go-rpm-macros-3.0.12 changed how it escapes quotes in the
gobuildflags macro, causing problems with how the fedora build worked.
But now %gomacro works with LDFLAGS and tags so switch to using that.
=> spec: Switch to using %gobuild macro on Fedora

.github/workflows/tests.yml
master branch doesn't exist anymore so I think it makes sense to change it to `main` which will hopefully also trigger the gitlab CI for main branch when a PR is merged.
=> tests: trigger on push to main

weldr/compose_test.go
Cancel when the build is in the wrong state now returns a proper error,
and ostree composes now accept the refid, parent, and the url without
returning an error.
=> tests: Update tests for osbuild-composer changes

.gitleaks.toml
This is a hashed password used only for testing, it's not used anywhere that matters. Exclude it from gitleaks reports.
=> gitleaks: Exclude the test password used in weldr-client

weldr-client.spec.in
See the relevant Fedora change:
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
We already verified that the SPDX format works well in the Enterprise Linux pipeline.
=> spec: migrate the license field to SPDX

weldr-client.spec.in
Added tmt tests to Fedora, and they depend on weldr-client-tests so switch the flag. If you do not want to build the integration tests, pass --without tests to rpmbuild.
=> Build weldr-client-tests by default

.github/workflows/tests.yml
We need to test with go 1.18.x and some of the vulnerabilities found aren't fixed until v1.19 or v1.20, so continue running the test but don't let failures count against the PR.
=> workflow: Ignore govulncheck failures

cmd/composer-cli/compose/start.go, cmd/composer-cli/compose/start_ostree.go, cmd/composer-cli/compose/start_ostree_test.go, cmd/composer-cli/compose/start_test.go, weldr/apischema.go, weldr/compose.go
osbuild-composer v79 can include a list of warning strings in the compose start result structure. This commit adds support for that to weldr/compose.go and to composer-cli which will print 'Warning: <string>' for each of them before printing the new compose UUID.
ComposeStartV0 has been changed to add a Warnings list of strings. Since this is an addition I didn't bump the API version. Callers should be testing the response Status flag to determine if the request was successful. It may now also contain Warnings when the flag is true.
The startCompose functions can return an APIResponse that includes the Warnings while also returning the UUID. In the future it may be possible to return errors and warnings, so the APIResponse Status flag should continue to be used to determine if the …
=> Add support for compose start warning messages

HACKING.md
Tittle says it all.
This PR cherry-picks a commit from https://github.com/osbuild/weldr-client/pull/99
=> docs: fix typo/formatting in HACKING.md

cmd/composer-cli/blueprints/blueprints.go, cmd/composer-cli/compose/compose.go, cmd/composer-cli/compose/start_ostree.go, cmd/composer-cli/sources/sources.go
The osbuild.org/guides page was restructured, so the links to it need to be updated to not result in 404s.
=> composer-cli: Update doc links

cmd/composer-cli/compose/info.go, cmd/composer-cli/compose/info_test.go, weldr/apischema.go
When an upload has been requested the info status contains details about the upload and whether or not it was successful. This adds a new section, 'Uploads' which lists the UUID, status, image name, and provider name.
=> info: Add upload status to the output

HACKING.md, README.md
The indented code blocks don't play nice with docusaurus, so when we import this page, that all looks out of place.
Similarly, the long title of the page doesn't look nice on the website.
=> README/HACKING.md: Update code block formatting and drop subtitle

.github/workflows/tests.yml, go.mod, tools/prepare-source.sh
We no longer need to support 1.19, switch to 1.20 and updated the github workflow and prepare-source.sh script.
=> go.mod: Use go 1.20

Containerfile.test, Makefile
rawhide now uses dnf5 which changes some builddep arguments
=> Fix testing which runs on rawhide

.github/workflows/tests.yml
go vuln doesn't support 1.20 anymore. It isn't required for tests to pass, so bump it to 1.21 even though we are still targeting 1.20, hopefully any errors it finds will be helpful in the future.
See:
* https://github.com/golang/go/issues/68034
* https://github.com/golang/vuln/commit/f35edf848bf0f2b9cf411833c60f72cc49915487
=> workflows: Use go 1.21.x for govuln tests

.github/workflows/tests.yml, go.mod, tools/prepare-source.sh
We no longer need to support 1.20, switch to 1.21 and update the github workflow and prepare-source.sh script. Drop 1.20 from the test matrix.
=> go.mod: Use go 1.21

README.md
docusaurus is used down-stream to embed this `README.md` into https://osbuild.org
without this - the page-local anchor links are broken
=> README: fix compatibility with docusaurus

cmd/composer-cli/compose/types_test.go, weldr/compose_test.go
On RHEL10 openstack has been removed, so change the test to look for qcow2 instead. Also remove it from test json and replace it with ami.
Resolves: RHEL-67056
=> tests: Remove openstack

cmd/composer-cli/blueprints/diff.go, cmd/composer-cli/root/root.go
go v1.24 will fail to build when non-constant strings are passed to the format field. Fix this now that that it doesn't become an issue when switching to v1.24
=> Fix non-constant log strings

weldr/compose_test.go
Use iot-qcow2-image for the integration test instead.
=> tests: OSTree does not support the qcow2 image type

README.md
Both projects are command line interfaces to
building images, it should be explained what the
difference is.
As soon as https://github.com/osbuild/osbuild.github.io/pull/151 lands, 
the projects are documented next to each other here https://osbuild.org/docs/developer-guide/projects/
so the difference between those two should be explained.
=> README.md: align with image-builder-cli
